# GET http://localhost:3003/api/fragrances?limit=19

# GET http://localhost:3003/api/fragrances/name?name=The Most Wanted
# GET http://localhost:3003/api/fragrances/brand?brand=Azzaro 
GET http://localhost:3003/api/fragrances/gender?gender=male 